export default function getItems() {
    return [
        {
            id: 1,
            rn: '1', // row number
            name: 'Полезное ископаемое, в т.ч.:',
            not: '1.jpg', // notation
            val: 'песок',  // value
            um: '', // unit of measure
            isInput: false,
            operands: {},
        },
        {
            id: 2,
            rn: '1.1',
            name: 'Песок мелкозернистый:',
            not: '',
            val: '',
            um: '',
            isInput: false,
            operands: {},
        },
        {
            id: 3,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '3.jpg',
            val: 0.2,
            um: '-',
            isInput: true,
            operands: {},
        },
        {
            id: 4,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '4.jpg',
            val: 91,
            um: '%',
            isInput: true,
            operands: {},
        },
        {
            id: 5,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.2,
            um: 'мм',
            isInput: true,
            operands: {},
        },
        {
            id: 6,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.3,
            um: 'доли ед.',
            isInput: true,
            operands: {},
        },
        {
            id: 7,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.65,
            um: 'т/м3',
            isInput: true,
            operands: {},
        },
        {
            id: 8,
            rn: '1.2',
            name: 'Пылеватые и глинистые частицы',
            not: '',
            val: '',
            um: '',
            isInput: false,
            operands: {},
        },
        {
            id: 9,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '9.jpg',
            val: 0.02,
            um: '-',
            isInput: true,
            operands: {},
        },
        {
            id: 10,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '10.jpg',
            val: 4.08,
            um: '%',
            isInput: true,
            operands: {},
        },
        {
            id: 11,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.1,
            um: 'мм',
            isInput: true,
            operands: {},
        },
        {
            id: 12,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.4,
            um: 'доли ед.',
            isInput: true,
            operands: {},
        },
        {
            id: 13,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.7,
            um: 'т/м3',
            isInput: true,
            operands: {},
        },
        {
            id: 14,
            rn: '1.3',
            name: 'Гравий',
            not: '',
            val: '',
            um: '',
            isInput: false,
            operands: {},
        },
        {
            id: 15,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '15.jpg',
            val: 0.8,
            um: '-',
            isInput: true,
            operands: {},
        },
        {
            id: 16,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '16.jpg',
            val: 4.42,
            um: '%',
            isInput: true,
            operands: {},
        },
        {
            id: 17,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.63,
            um: 'мм',
            isInput: true,
            operands: {},
        },
        {
            id: 18,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.3,
            um: 'доли ед.',
            isInput: true,
            operands: {},
        },
        {
            id: 19,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.65,
            um: 'т/м3',
            isInput: true,
            operands: {},
        },
        {
            id: 20,
            rn: '2',
            name: 'Общий объем добычи за весь период разработки карьера',
            not: '20.jpg',
            val: 13959359,
            um: 'м3',
            isInput: true,
            operands: {},
        },
        {
            id: 21,
            rn: '2.1',
            name: 'Сезонный объем добычи',
            not: '21.jpg',
            val: 664740,
            um: 'м3',
            isInput: true,
            operands: {},
        },
        {
            id: 22,
            rn: '3',
            name: 'Средняя плотность породы в естественном залегании',
            not: '22.jpg',
            val: 1.6,
            um: 'т/м3',
            isInput: true,
            operands: {},
        },
        {
            id: 23,
            rn: '4',
            name: 'Удельный расход воды на разработку грунта',
            not: '23.jpg',
            val: 7,
            um: 'м3/м3',
            isInput: true,
            operands: {},
        },
        {
            id: 24,
            rn: '5',
            name: 'Плотность воды',
            not: '24.jpg',
            val: 1,
            um: 'т/м3',
            isInput: true,
            operands: {},
        },
        {
            id: 25,
            rn: '6',
            name: 'Тип земснаряда',
            not: '',
            val: 'Гидромех 2000',
            um: '',
            isInput: false,
            operands: {},
        },
        {
            id: 26,
            rn: '7',
            name: 'Диаметр пульпопровода',
            not: '26.jpg',
            val: 0.426,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 27,
            rn: '8',
            name: 'Диаметр всасывающей трубы',
            not: '27.jpg',
            val: 0.6,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 28,
            rn: '9',
            name: 'Длина плавучего участка магистрального пульпопровода',
            not: '28.jpg',
            val: 200,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 29,
            rn: '10',
            name: 'Длина участка берегового магистрального пульпопровода до карты намыва',
            not: '29.jpg',
            val: 700,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 30,
            rn: '11',
            name: 'Длина наклонного участка пульпопровода при переходе от плавучего к магистральному',
            not: '30.jpg',
            val: 30,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 31,
            rn: '12',
            name: 'Угол наклона трубы (борта карьера)',
            not: '31.jpg',
            val: 30,
            um: 'град',
            isInput: true,
            operands: {},
        },
        {
            id: 32,
            rn: '13',
            name: 'Длина намывного распределительного пульпопровода на картах намыва',
            not: '32.jpg',
            val: 150,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 33,
            rn: '14',
            name: 'Грунтовый насос',
            not: '1.jpg',
            val: 'ГРаУ 2000-63',
            um: '',
            isInput: false,
            operands: {},
        },
        {
            id: 34,
            rn: '15',
            name: 'Подача грунтового насоса по воде',
            not: '34.jpg',
            val: 2000,
            um: 'м3/ч',
            isInput: true,
            operands: {},
        },
        {
            id: 35,
            rn: '16',
            name: 'Напор насоса',
            not: '35.jpg',
            val: 63,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 36,
            rn: '17',
            name: 'Геодезическая высота всасывания',
            not: '36.jpg',
            val: -0.5,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 37,
            rn: '18',
            name: 'Глубина разработки грунта',
            not: '37.jpg',
            val: 13.5,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 38,
            rn: '19',
            name: 'Высота подъема гидросмеси',
            not: '38.jpg',
            val: 10,
            um: 'м',
            isInput: true,
            operands: {},
        },
        {
            id: 39,
            rn: '20',
            name: 'Продолжительность смены',
            not: '39.jpg',
            val: 8,
            um: 'ч',
            isInput: true,
            operands: {},
        },
        {
            id: 40,
            rn: '21',
            name: 'Число рабочих смен в сутки',
            not: '40.jpg',
            val: 2,
            um: '',
            isInput: true,
            operands: {},
        },
        {
            id: 41,
            rn: '1',
            name: 'Средняя плотность гидросмеси',
            not: '41.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: '(((x+y+z)/3)*(1-(a+b+c)/3)+k*t)/((1-(a+b+c)/3)+t)',
            operands: { a: 6, b: 12, c: 18, x: 7, y: 13, z: 19, k: 24, t: 23 },
        },
    ];
}