export default function getItems() {
    return [
        {
            id: 1,
            block: 1,
            rn: '1', // row number
            name: 'Полезное ископаемое, в т.ч.:',
            not: '1.jpg', // notation
            val: 'песок',  // value
            um: '', // unit of measure
            isInput: true,
            calcOrder: 0,
            type: 'text'
        },
        {
            id: 2,
            block: 1,
            rn: '1.1',
            name: 'Песок мелкозернистый:',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 3,
            block: 1,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '3.jpg',
            val: 0.2,
            um: '-',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 4,
            block: 1,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '4.jpg',
            val: 91,
            um: '%',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 5,
            block: 1,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.2,
            um: 'мм',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 6,
            block: 1,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.3,
            um: 'доли ед.',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 7,
            block: 1,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.65,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 8,
            block: 1,
            rn: '1.2',
            name: 'Пылеватые и глинистые частицы',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 9,
            block: 1,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '9.jpg',
            val: 0.02,
            um: '-',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 10,
            block: 1,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '10.jpg',
            val: 4.08,
            um: '%',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 11,
            block: 1,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.1,
            um: 'мм',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 12,
            block: 1,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.4,
            um: 'доли ед.',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 13,
            block: 1,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.7,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 14,
            block: 1,
            rn: '1.3',
            name: 'Гравий',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 15,
            block: 1,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '15.jpg',
            val: 0.8,
            um: '-',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 16,
            block: 1,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '16.jpg',
            val: 4.42,
            um: '%',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 17,
            block: 1,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.63,
            um: 'мм',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 18,
            block: 1,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.3,
            um: 'доли ед.',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 19,
            block: 1,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.65,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 20,
            block: 1,
            rn: '2',
            name: 'Общий объем добычи за весь период разработки карьера',
            not: '20.jpg',
            val: 13959359,
            um: 'м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 21,
            block: 1,
            rn: '2.1',
            name: 'Сезонный объем добычи',
            not: '21.jpg',
            val: 664740,
            um: 'м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 22,
            block: 1,
            rn: '3',
            name: 'Средняя плотность породы в естественном залегании',
            not: '22.jpg',
            val: 1.6,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 23,
            block: 1,
            rn: '4',
            name: 'Удельный расход воды на разработку грунта',
            not: '23.jpg',
            val: 7,
            um: 'м3/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 24,
            block: 1,
            rn: '5',
            name: 'Плотность воды',
            not: '24.jpg',
            val: 1,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 25,
            block: 1,
            rn: '6',
            name: 'Тип земснаряда',
            not: '',
            val: 'Гидромех 2000',
            um: '',
            isInput: true,
            calcOrder: 0,
            type: 'text'
        },
        {
            id: 26,
            block: 1,
            rn: '7',
            name: 'Диаметр пульпопровода',
            not: '26.jpg',
            val: 0.426,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 27,
            block: 1,
            rn: '8',
            name: 'Диаметр всасывающей трубы',
            not: '27.jpg',
            val: 0.6,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 28,
            block: 1,
            rn: '9',
            name: 'Длина плавучего участка магистрального пульпопровода',
            not: '28.jpg',
            val: 200,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 29,
            block: 1,
            rn: '10',
            name: 'Длина участка берегового магистрального пульпопровода до карты намыва',
            not: '29.jpg',
            val: 700,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 30,
            block: 1,
            rn: '11',
            name: 'Длина наклонного участка пульпопровода при переходе от плавучего к магистральному',
            not: '30.jpg',
            val: 30,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 31,
            block: 1,
            rn: '12',
            name: 'Угол наклона трубы (борта карьера)',
            not: '31.jpg',
            val: 30,
            um: 'град',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 32,
            block: 1,
            rn: '13',
            name: 'Длина намывного распределительного пульпопровода на картах намыва',
            not: '32.jpg',
            val: 150,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 33,
            block: 1,
            rn: '14',
            name: 'Грунтовый насос',
            not: '1.jpg',
            val: 'ГРаУ 2000-63',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 34,
            block: 1,
            rn: '15',
            name: 'Подача грунтового насоса по воде',
            not: '34.jpg',
            val: 2000,
            um: 'м3/ч',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 35,
            block: 1,
            rn: '16',
            name: 'Напор насоса',
            not: '35.jpg',
            val: 63,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 36,
            block: 1,
            rn: '17',
            name: 'Геодезическая высота всасывания',
            not: '36.jpg',
            val: -0.5,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 37,
            block: 1,
            rn: '18',
            name: 'Глубина разработки грунта',
            not: '37.jpg',
            val: 13.5,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 38,
            block: 1,
            rn: '19',
            name: 'Высота подъема гидросмеси',
            not: '38.jpg',
            val: 10,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 39,
            block: 1,
            rn: '20',
            name: 'Продолжительность смены',
            not: '39.jpg',
            val: 8,
            um: 'ч',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 40,
            block: 1,
            rn: '21',
            name: 'Число рабочих смен в сутки',
            not: '40.jpg',
            val: 2,
            um: '',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 41,
            block: 2,
            rn: '1',
            name: 'Средняя плотность гидросмеси:',
            not: '41.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: '(y*q+u*(1-m))/(q+(1-m))',
            operands: { y: 42, q: 43, u: 45, m: 44 },
            round: 3,
            calcOrder: 5,
            parent: 0,
        },
        {
            id: 42,
            block: 2,
            rn: 'где:',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 24 },
            calcOrder: 1,
            parent: 41,
        },
        {
            id: 43,
            block: 2,
            rn: '',
            name: 'удельный расход воды',
            not: '23.jpg',
            val: '',
            um: 'м3/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 23 },
            calcOrder: 2,
            parent: 41,
            comment: 'табл. 2.22 ОНТП 18-85'
        },
        {
            id: 44,
            block: 2,
            rn: '',
            name: 'средняя пористость породы, доли ед',
            not: '44.jpg',
            val: '',
            um: 'доли ед.',
            isInput: false,
            formula: '(x+y+z)/3',
            operands: { x: 6, y: 12, z: 18 },
            calcOrder: 3,
            parent: 41,
        },
        {
            id: 45,
            block: 2,
            rn: '',
            name: 'средняя плотность частиц породы',
            not: '45.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: '(x+y+z)/3',
            operands: { x: 7, y: 13, z: 19 },
            calcOrder: 4,
            parent: 41,
        },
        {
            id: 46,
            block: 2,
            rn: '2',
            name: 'Производительность земснаряда по гидросмеси:',
            not: '46.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x/y',
            operands: { x: 47, y: 48 },
            calcOrder: 8,
            parent: 0,
        },
        {
            id: 47,
            block: 2,
            rn: 'где:',
            name: 'подача грунтового насоса по воде, м3/ч',
            not: '47.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 34 },
            calcOrder: 6,
            parent: 46,
        },
        {
            id: 48,
            block: 2,
            rn: '',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 41 },
            round: 3,
            calcOrder: 7,
            parent: 46,
        },
        {
            id: 49,
            block: 2,
            rn: '3',
            name: 'Расчетная техническая производительность земснаряда по породе (грунту):',
            not: '49.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x/(q+(1-m))',
            operands: { x: 50, q: 51, m: 52 },
            round: 0,
            calcOrder: 12,
            parent: 0,
        },
        {
            id: 50,
            block: 2,
            rn: 'где:',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },  
            calcOrder: 9,
            parent: 49,
        },
        {
            id: 51,
            block: 2,
            rn: '',
            name: 'удельный расход воды',
            not: '23.jpg',
            val: '',
            um: 'м3/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 43 },
            calcOrder: 10,
            parent: 49,
        },
        {
            id: 52,
            block: 2,
            rn: '',
            name: 'средняя пористость породы, доли ед',
            not: '44.jpg',
            val: '',
            um: 'доли ед.',
            isInput: false,
            formula: 'x',
            operands: { x: 44 },
            calcOrder: 11,
            parent: 49,
        },
        {
            id: 53,
            block: 2,
            rn: '4',
            name: 'Расчетная сменная производительность земснаряда по грунту:',
            not: '53.jpg',
            val: '',
            um: 'м3/смена',
            isInput: false,
            formula: 'x*t*k*l*m*n',
            operands: { x: 54, t: 55, k: 56, l: 57, m: 58, n: 59 },
            round: 0,
            calcOrder: 15,
            parent: 0,
        },
        {
            id: 54,
            block: 2,
            rn: 'где:',
            name: 'расчетная техническая производительность земснаряда по породе (грунту)',
            not: '54.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 49 },
            calcOrder: 13,
            round: 0,
            parent: 53,
        },
        {
            id: 55,
            block: 2,
            rn: '',
            name: 'продолжительность смены',
            not: '39.jpg',
            val: '',
            um: 'ч',
            isInput: false,
            formula: 'x',
            operands: { x: 39 },
            calcOrder: 14,
            parent: 53,
        },
        {
            id: 56,
            block: 2,
            rn: '',
            name: 'коэффициент использования внутрисменного времени',
            not: '56.jpg',
            val: 0.75,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 57,
            block: 2,
            rn: '',
            name: 'коэффициент учитывающий межсменные и другие простои',
            not: '57.jpg',
            val: 0.95,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 58,
            block: 2,
            rn: '',
            name: 'коэффициент, учитывающий засоренность забоя',
            not: '58.jpg',
            val: 1.00,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 59,
            block: 2,
            rn: '',
            name: 'коэффициент, учитывающий работу земснаряда совместно со станциями перекачивания',
            not: '59.jpg',
            val: 1.00,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 60,
            block: 2,
            rn: '5',
            name: 'Количество машиносмен на добычных работах для одного земснаряда за один сезон разработки карьера:',
            not: '60.jpg',
            val: '',
            um: 'машиносмен',
            isInput: false,
            formula: 'x/y',
            operands: { x: 61, y: 62 },
            round: 0,
            calcOrder: 18,
            parent: 0,
        },
        {
            id: 61,
            block: 2,
            rn: 'где:',
            name: 'сезонный объем добычи',
            not: '61.jpg',
            val: '',
            um: 'м3',
            isInput: false,
            formula: 'x',
            operands: { x: 21 },
            calcOrder: 16,
            parent: 60,
        },
        {
            id: 62,
            block: 2,
            rn: '',
            name: 'расчетная сменная производительность земснаряда по грунту',
            not: '62.jpg',
            val: '',
            um: 'м3/смена',
            isInput: false,
            formula: 'x',
            operands: { x: 53 },
            calcOrder: 17,
            parent: 60,
        },
        {
            id: 63,
            block: 2,
            rn: '6',
            name: 'Количество машиносмен на добычных работах для одного земснаряда за весь период разработки карьера:',
            not: '63.jpg',
            val: '',
            um: 'машиносмен',
            isInput: false,
            formula: 'x/y',
            operands: { x: 64, y: 65 },
            round: 0,
            calcOrder: 21,
            parent: 0,
        },
        {
            id: 64,
            block: 2,
            rn: 'где:',
            name: 'общий объем добычи за весь период разработки карьера',
            not: '64.jpg',
            val: '',
            um: 'м3',
            isInput: false,
            formula: 'x',
            operands: { x: 20 },
            calcOrder: 19,
            parent: 63,
        },
        {
            id: 65,
            block: 2,
            rn: '',
            name: 'расчетная сменная производительность земснаряда по грунту',
            not: '65.jpg',
            val: '',
            um: 'м3/сутки',
            isInput: false,
            formula: 'x',
            operands: { x: 53 },
            calcOrder: 20,
            parent: 63,
        },
        {
            id: 66,
            block: 2,
            rn: '7',
            name: 'Расход воды для обеспечения земснаряда:',
            not: '66.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x*q+y',
            operands: { x: 67, q: 68, y: 69 },
            round: 0,
            calcOrder: 25,
            parent: 0,
        },
        {
            id: 67,
            block: 2,
            rn: 'где:',
            name: 'расчетная производительность земснаряда по грунту',
            not: '54.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 49 },
            calcOrder: 22,
            parent: 66,
        },
        {
            id: 68,
            block: 2,
            rn: '',
            name: 'удельный расход воды',
            not: '23.jpg',
            val: '',
            um: 'м3/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 23 },
            calcOrder: 23,
            parent: 66,
        },
        {
            id: 69,
            block: 2,
            rn: '',
            name: 'сумма потерь воды на фильтрацию и испарение',
            not: '69.jpg',
            val: '',
            um: 'м3',
            isInput: false,
            formula: '0.1*x*y',
            operands: { x: 67, y: 68 },
            calcOrder: 24,
            parent: 66,
            comment: '10% от ',
            commentImg: '69c.jpg'
        },
        {
            id: 70,
            block: 3,
            rn: '1',
            name: 'Средневзвешенный коэффициент транспортабельности:',
            not: '70.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: '(x*a + y*b + z*c)/100',
            operands: { x: 3, a: 4, y: 9, b: 10, z: 15, c: 16 },
            calcOrder: 26,
            parent: 0,
        },
        {
            id: 71,
            block: 3,
            rn: 'где:',
            name: 'коэффиценты транспортабельности фракций для каждого слоя',
            not: '71.jpg',
            val: '',
            um: '-',
            isInput: false,
            calcOrder: 0,
            parent: 71,
        },
        {
            id: 72,
            block: 3,
            rn: '',
            name: 'процентное содержание в толще для каждого слоя',
            not: '72.jpg',
            val: '',
            um: '%',
            isInput: false,
            calcOrder: 0,
            parent: 71,
        },
        {
            id: 73,
            block: 3,
            rn: '2',
            name: 'Критическая скорость гидросмеси в пульповоде, м/с:',
            not: '73.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: '8*pow(x,1/3)*pow(y*z,1/6)',
            operands: { x: 74, y: 75, z: 76 },
            calcOrder: 34,
            round: 2,
            parent: 0,
        },
        {
            id: 74,
            block: 3,
            rn: 'где:',
            name: 'диаметр пульпопровода',
            not: '26.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 26 },
            calcOrder: 31,
            round: 3,
            parent: 73,
        },
        {
            id: 75,
            block: 3,
            rn: '',
            name: ' объемная консистенция гидросмеси',
            not: '75.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 77 },
            calcOrder: 32,
            round: 3,
            parent: 73,
        },
        {
            id: 76,
            block: 3,
            rn: '',
            name: 'средневзвешенный коэффициент транспортабельности',
            not: '76.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 70 },
            calcOrder: 33,
            parent: 73,
        },
        {
            id: 77,
            block: 3,
            rn: '3',
            name: 'Объемная консистенция гидросмеси:',
            not: '77.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: '(x-a)/(y-a)',
            operands: { x: 41, a: 24, y: 45 },
            calcOrder: 30,
            round: 3,
            parent: 0,
        },
        {
            id: 78,
            block: 3,
            rn: 'где:',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 41 },
            calcOrder: 27,
            parent: 77,
        },
        {
            id: 79,
            block: 3,
            rn: '',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 24 },
            calcOrder: 28,
            parent: 77,
        },
        {
            id: 80,
            block: 3,
            rn: '',
            name: 'средняя плотность частиц породы',
            not: '45.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 45 },
            calcOrder: 29,
            parent: 77,
        },
        {
            id: 81,
            block: 3,
            rn: '4',
            name: 'Действительная скорость в пульпопроводе:',
            not: '81.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: '(4*x)/(3.14*y*y*3600)',
            operands: { x: 82, y: 83 },
            calcOrder: 37,
            parent: 0,
        },
        {
            id: 82,
            block: 3,
            rn: 'где:',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },
            calcOrder: 35,
            parent: 81,
        },
        {
            id: 83,
            block: 3,
            rn: '',
            name: 'диаметр пульпопровода',
            not: '26.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 26 },
            round: 3,
            calcOrder: 36,
            parent: 81,
        },
        {
            id: 84,
            block: 3,
            rn: '5',
            name: 'Проверка отношения действительной скорости к критической:',
            not: '84.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x/y',
            operands: { x: 81, y: 73 },
            calcOrder: 38,
            parent: 0,
            comment: 'Проверка условия',
            commentImg: '84c.jpg'
        },
        {
            id: 85,
            block: 3,
            rn: '6',
            name: 'Оптимальная скорость в пульпопроводе при заданном диаметре:',
            not: '85.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: '5.5*pow((x*y*z),1/6)',
            operands: { x: 86, y: 87, z: 88 },
            calcOrder: 42,
            parent: 0,
        },
        {
            id: 86,
            block: 3,
            rn: 'где:',
            name: 'объемная консистенция гидросмеси',
            not: '75.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 77 },
            calcOrder: 39,
            parent: 85,
        },
        {
            id: 87,
            block: 3,
            rn: '',
            name: 'средневзвешенный коэффициент транспортабельности',
            not: '76.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 76 },
            calcOrder: 40,
            parent: 85,
        },
        {
            id: 88,
            block: 3,
            rn: '',
            name: 'диаметр пульпопровода',
            not: '26.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 26 },
            round: 3,
            calcOrder: 41,
            parent: 85,
        },
        {
            id: 89,
            block: 3,
            rn: '7',
            name: 'Удельные потери напора при движении гидросмеси:',
            not: '89.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'i*(1+2*pow(x/y,3))',
            operands: { i: 90, x: 85, y: 81 },
            round: 3,
            calcOrder: 47,
            parent: 0,
        },
        {
            id: 90,
            block: 3,
            rn: 'где:',
            name: 'удельные потери напора при движении воды в пульповоде',
            not: '90.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '(x*v*v)/(2*9.8*d)',
            operands: { x: 93, v: 81, d: 83 },
            round: 3,
            calcOrder: 43,
            parent: 89,
        },
        {
            id: 91,
            block: 3,
            rn: '',
            name: 'оптимальная скорость в пульпопроводе',
            not: '91.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 85 },
            calcOrder: 44,
            parent: 89,
        },
        {
            id: 92,
            block: 3,
            rn: '',
            name: 'действительная скорость в пульпопроводе',
            not: '92.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 81 },
            calcOrder: 45,
            parent: 89,
        },
        {
            id: 93,
            block: 3,
            rn: '',
            name: 'коэффициент гидравлических сопротивлений',
            not: '93.jpg',
            val: 0.0115,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 89,
        },
        {
            id: 94,
            block: 3,
            rn: '',
            name: 'диаметр пульпопровода',
            not: '26.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 26 },
            round: 3,
            calcOrder: 46,
            parent: 89,
        },
        {
            id: 95,
            block: 3,
            rn: '',
            name: 'ускорение свободного падения',
            not: '95.jpg',
            val: '9.80',
            um: 'м/с2',
            isInput: false,           
            calcOrder: 0,
            parent: 89,
        },
        {
            id: 96,
            block: 3,
            rn: '8',
            name: 'Потери напора, м, во всасывающем трубопроводе земснаряда:',
            not: '96.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'h*a/b+k*(a/b-1)+i*l+m+v*v/(2*9.8)*(a/b)+j',
            operands: { h: 97, a: 98, b: 99, k: 100, i: 110, l: 103, m: 101, v: 106, j: 105 },
            calcOrder: 69,
            parent: 0,
        },
        {
            id: 97,
            block: 3,
            rn: 'где:',
            name: 'геодезическая высота всасывания',
            not: '36.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 36 },
            calcOrder: 64,
            parent: 96,
        },
        {
            id: 98,
            block: 3,
            rn: '',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 41 },
            calcOrder: 65,
            parent: 96,
        },
        {
            id: 99,
            block: 3,
            rn: '',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 42 },
            calcOrder: 66,
            parent: 96,
        },
        {
            id: 100,
            block: 3,
            rn: '',
            name: 'глубина разработки',
            not: '37.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 37 },
            calcOrder: 67,
            parent: 96,
        },
        {
            id: 101,
            block: 3,
            rn: '',
            name: 'местные потери напора во всасывающей трубе',
            not: '101.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '0.1*x',
            operands: { x: 102 },
            calcOrder: 63,
            parent: 96,
        },
        {
            id: 102,
            block: 3,
            rn: 'где:',
            name: '',
            not: '102.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'i*x',
            operands: { i: 103, x: 109 },
            calcOrder: 62,
            parent: 96,
        },
        {
            id: 103,
            block: 3,
            rn: '',
            name: 'длина всасывающей трубы',
            not: '103.jpg',
            val: '20.00',
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 96,
        },
        {
            id: 104,
            block: 3,
            rn: '',
            name: 'скорость во всасывающей трубе',
            not: '104.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 106 },
            calcOrder: 68,
            parent: 96,
        },
        {
            id: 105,
            block: 3,
            rn: '',
            name: 'потери напора в щели всасывания',
            not: '105.jpg',
            val: '1.00',
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 96,
        },
        {
            id: 106,
            block: 3,
            rn: '9',
            name: 'Скорость во всасывающей трубе:',
            not: '106.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: '(4*q)/(3.14*d*d*3600)',
            operands: { q: 107, d: 108 },
            calcOrder: 50,
            parent: 0,
        },
        {
            id: 107,
            block: 3,
            rn: 'где:',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },
            calcOrder: 48,
            parent: 106,
        },
        {
            id: 108,
            block: 3,
            rn: '',
            name: 'диаметр всасывающей трубы',
            not: '27.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 27 },
            calcOrder: 49,
            parent: 106,
        },
        {
            id: 109,
            block: 3,
            rn: '10',
            name: 'Удельные потери напора во всасывающей трубе:',
            not: '109.jpg',
            val: '',
            um: 'м/м',
            isInput: false,
            formula: 'i*(1+2*pow(x/y,3))',
            operands: { i: 116, x: 112, y: 106 },
            round: 3,
            calcOrder: 61,
            parent: 0,
        },
        {
            id: 110,
            block: 3,
            rn: 'где:',
            name: 'удельные потери напора во всасывающей трубе',
            not: '110.jpg',
            val: '',
            um: 'м/м',
            isInput: false,
            formula: 'x',
            operands: { x: 116 },
            round: 4,
            calcOrder: 55,
            parent: 109,
        },
        {
            id: 111,
            block: 3,
            rn: '',
            name: 'скорость во всасывающей трубе',
            not: '111.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 106 },
            calcOrder: 56,
            parent: 109,
        },
        {
            id: 112,
            block: 3,
            rn: '',
            name: 'оптимальная скорость во всасывающем трубопроводе',
            not: '112.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: '5.5*pow(s*x*y,1/6)',
            operands: { s: 77, x: 70, y: 108 },
            calcOrder: 57,
            parent: 109,
        },
        {
            id: 113,
            block: 3,
            rn: '',
            name: 'диаметр всасывающей трубы',
            not: '27.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 27 },
            calcOrder: 58,
            parent: 109,
        },
        {
            id: 114,
            block: 3,
            rn: '',
            name: 'объемная консистенция гидросмеси',
            not: '75.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 77 },
            calcOrder: 59,
            parent: 109,
        },
        {
            id: 115,
            block: 3,
            rn: '',
            name: 'средневзвешенный коэффициент транспортабельности',
            not: '76.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 76 },
            calcOrder: 60,
            parent: 109,
        },
        {
            id: 116,
            block: 3,
            rn: '11',
            name: 'Удельные потери напора во всасывающей трубе:',
            not: '116.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: '(l*v*v)/(2*9.8*d)',
            operands: { l: 117, v: 118, d: 119 },
            round: 4,
            calcOrder: 54,
            parent: 0,
        },
        {
            id: 117,
            block: 3,
            rn: 'где:',
            name: 'коэффициент гидравлических сопротивлений',
            not: '93.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 93 },
            round: 4,
            calcOrder: 51,
            parent: 116,
        },
        {
            id: 118,
            block: 3,
            rn: '',
            name: 'скорость во всасывающей трубе',
            not: '111.jpg',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 106 },
            calcOrder: 52,
            parent: 116,
        },
        {
            id: 119,
            block: 3,
            rn: '',
            name: 'диаметр всасывающей трубы',
            not: '27.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 27 },
            calcOrder: 53,
            parent: 116,
        },
        {
            id: 120,
            block: 3,
            rn: '12',
            name: 'Потери напора в гидротранспортной системе:',
            not: '120.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '(a+b+c+d+e+f+j+k)',
            operands: { a: 121, b: 122, c: 123, d: 124, e: 125, f: 126, j: 127, k: 128 },
            calcOrder: 107,
            parent: 0,
        },
        {
            id: 121,
            block: 3,
            rn: 'где:',
            name: 'потери напора во всасывающем трубопроводе',
            not: '121.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a',
            operands: { a: 96 },
            calcOrder: 100,
            parent: 120,
        },
        {
            id: 122,
            block: 3,
            rn: '',
            name: 'потери напора в плавучем трубопроводе',
            not: '122.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a',
            operands: { a: 129 },
            calcOrder: 101,
            parent: 120,
        },
        {
            id: 123,
            block: 3,
            rn: '',
            name: 'потери напора в наклонном трубопроводе',
            not: '123.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a',
            operands: { a: 132 },
            calcOrder: 102,
            parent: 120,
        },
        {
            id: 124,
            block: 3,
            rn: '',
            name: 'потери напора в намывном трубопроводе на раструбных соединениях',
            not: '124.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a',
            operands: { a: 137 },
            calcOrder: 103,
            parent: 120,
        },
        {
            id: 125,
            block: 3,
            rn: '',
            name: 'потери напора на горизонтальных участках магистрального трубопровода',
            not: '125.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a',
            operands: { a: 140 },
            calcOrder: 104,
            parent: 120,
        },
        {
            id: 126,
            block: 3,
            rn: '',
            name: 'потери напора на подъем гидросмеси (геодезия подъема гидросмеси)',
            not: '126.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a',
            operands: { a: 143 },
            calcOrder: 105,
            parent: 120,
        },
        {
            id: 127,
            block: 3,
            rn: '',
            name: 'местные потери напора в трубопроводе',
            not: '127.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a',
            operands: { a: 147 },
            calcOrder: 106,
            parent: 120,
        },
        {
            id: 128,
            block: 3,
            rn: '',
            name: 'остаточный напор на конце трубопровода',
            not: '128.jpg',
            val: '3.00',
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 120,
        },
        {
            id: 129,
            block: 3,
            rn: '13',
            name: 'Потери напора в плавучем пульпопроводе:',
            not: '129.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '2*x*y',
            operands: { x: 130 , y: 131 },
            calcOrder: 72,
            parent: 0,
        },
        {
            id: 130,
            block: 3,
            rn: 'где:',
            name: 'удельные потери напора при движении гидросмеси',
            not: '130.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 89 },
            calcOrder: 70,
            parent: 129,
        },
        {
            id: 131,
            block: 3,
            rn: '',
            name: 'длина плавучего пульпопровода',
            not: '28.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 28 },
            calcOrder: 71,
            parent: 129,
        },
        {
            id: 132,
            block: 3,
            rn: '14',
            name: 'Потери напора в наклонном трубопроводе:',
            not: '132.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '(o+(n-o)*cos(a*3.14/180))*l',
            operands: { o: 133, n: 134, a: 135, l: 136 },
            calcOrder: 77,
            parent: 0,
        },
        {
            id: 133,
            block: 3,
            rn: 'где:',
            name: 'удельные потери напора при движении воды в пульпопроводе',
            not: '133.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 90 },
            round: 3,
            calcOrder: 73,
            parent: 132,
        },
        {
            id: 134,
            block: 3,
            rn: '',
            name: 'удельные потери напора при движении гидросмеси',
            not: '130.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 89 },
            round: 3,
            calcOrder: 74,
            parent: 132,
        },
        {
            id: 135,
            block: 3,
            rn: '',
            name: 'угол наклона трубы',
            not: '31.jpg',
            val: '',
            um: 'град.',
            isInput: false,
            formula: 'x',
            operands: { x: 31 },
            calcOrder: 75,
            parent: 132,
        },
        {
            id: 136,
            block: 3,
            rn: '',
            name: 'длина наклонного участка трубы при переходе от плавучего пульпопровода к береговому (магистральному)',
            not: '30.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 30 },
            calcOrder: 76,
            parent: 132,
        },
        {
            id: 137,
            block: 3,
            rn: '15',
            name: 'Потери напора в намывном трубопроводе на раструбных соединениях:',
            not: '137.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '1.5*x*y',
            operands: { x: 138, y: 139 },
            calcOrder: 80,
            parent: 0,
        },
        {
            id: 138,
            block: 3,
            rn: 'где:',
            name: 'удельные потери напора при движении гидросмеси',
            not: '130.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 89 },
            round: 3,
            calcOrder: 78,
            parent: 137,
        },
        {
            id: 139,
            block: 3,
            rn: '',
            name: 'длина намывного трубопровода на картах намыва',
            not: '32.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 32 },
            calcOrder: 79,
            parent: 137,
        },
        {
            id: 140,
            block: 3,
            rn: '16',
            name: 'Потери напора в магистральном пульпопроводе на горизонтальных участках:',
            not: '140.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x*y',
            operands: { x: 141, y: 142 },
            calcOrder: 83,
            parent: 0,
        },
        {
            id: 141,
            block: 3,
            rn: 'где:',
            name: 'удельные потери напора при движении гидросмеси',
            not: '130.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 89 },
            round: 3,
            calcOrder: 81,
            parent: 140,
        },
        {
            id: 142,
            block: 3,
            rn: '',
            name: 'длина горизонтальных участков магистрального трубопровода',
            not: '29.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 29 },
            calcOrder: 82,
            parent: 140,
        },
        {
            id: 143,
            block: 3,
            rn: '17',
            name: 'Потери напора на подъем гидросмеси (геодезия подъема гидросмеси):',
            not: '143.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'h*x/y',
            operands: { h: 144, x: 145, y: 146 },
            calcOrder: 87,
            parent: 0,
        },
        {
            id: 144,
            block: 3,
            rn: 'где:',
            name: 'высота подъема гидросмеси',
            not: '38.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 38 },           
            calcOrder: 84,
            parent: 143,
        },
        {
            id: 145,
            block: 3,
            rn: '',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 48 },
            round: 3,
            calcOrder: 85,
            parent: 143,
        },
        {
            id: 146,
            block: 3,
            rn: '',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 24 },
            calcOrder: 86,
            parent: 143,
        },
        {
            id: 147,
            block: 3,
            rn: '18',
            name: 'Местные потери напора в трубопроводе:',
            not: '147.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '0.1*(a+b+c+d)',
            operands: { a: 148, b: 149, c: 150, d: 151 },
            calcOrder: 92,
            parent: 0,
        },
        {
            id: 148,
            block: 3,
            rn: 'где:',
            name: 'потери напора в плавучем трубопроводе',
            not: '148.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 129 },
            calcOrder: 88,
            parent: 147,
        },
        {
            id: 149,
            block: 3,
            rn: '',
            name: 'потери напора в наклонном трубопроводе',
            not: '149.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 132 },
            round: 3,
            calcOrder: 89,
            parent: 147,
        },
        {
            id: 150,
            block: 3,
            rn: '',
            name: 'потери напора в намывном трубопроводе на раструбных соединениях',
            not: '150.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 137 },
            calcOrder: 90,
            parent: 147,
        },
        {
            id: 151,
            block: 3,
            rn: '',
            name: 'потери напора на горизонтальных участках',
            not: '151.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 140 },
            calcOrder: 91,
            parent: 147,
        },
        {
            id: 152,
            block: 3,
            rn: '19',
            name: 'Число грунтовых насосов в гидротранспортной системе для обеспечения необходимого напора:',
            not: '152.jpg',
            val: '',
            um: 'шт',
            isInput: false,
            formula: 'ceil(x/y)',
            operands: { x: 153, y: 154 },
            calcOrder: 109,
            parent: 0,
            comment: 'Округл. до целового в большую сторону'
        },
        {
            id: 153,
            block: 3,
            rn: 'где:',
            name: 'потери напора в гидротранспортной системе',
            not: '153.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 120 },
            calcOrder: 108,
            parent: 152,
        },
        {
            id: 154,
            block: 3,
            rn: '20',
            name: 'Напор земснаряда по гидросмеси:',
            not: '154.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'a*(x/y)*b',
            operands: { a: 155, x: 156, y: 157, b: 158 },
            calcOrder: 99,
            parent: 0,
        },
        {
            id: 155,
            block: 3,
            rn: 'где:',
            name: 'напор земснаряда по воде',
            not: '35.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 35 },
            calcOrder: 93,
            parent: 154,
        },
        {
            id: 156,
            block: 3,
            rn: '',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 48 },
            calcOrder: 94,
            parent: 154,
        },
        {
            id: 157,
            block: 3,
            rn: '',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 24 },
            calcOrder: 95,
            parent: 154,
        },
        {
            id: 158,
            block: 3,
            rn: '',
            name: 'коэффициент, учитывающий дополнительные гидравлические потери в грунтовом насосе',
            not: '158.jpg',
            val: '',
            um: '',
            isInput: false,
            formula: '1-0.05*(x-y)/y*k*l',
            operands: { x: 159, y: 160, k: 161, l: 162 },
            calcOrder: 98,
            parent: 154,
        },
        {
            id: 159,
            block: 3,
            rn: 'где:',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 48 },
            calcOrder: 96,
            parent: 154,
        },
        {
            id: 160,
            block: 3,
            rn: '',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 24 },
            calcOrder: 97,
            parent: 154,
        },
        {
            id: 161,
            block: 3,
            rn: '',
            name: 'коэффициент влияния грунта',
            not: '161.jpg',
            val: '0.75',
            um: '',
            isInput: true,
            calcOrder: 0,
            parent: 154,
        },
        {
            id: 162,
            block: 3,
            rn: '',
            name: 'поправочный коэффициент влияющий от марки землесоса',
            not: '162.jpg',
            val: '19.00',
            um: '',
            isInput: true,
            calcOrder: 0,
            parent: 154,
        },
        {
            id: 163,
            block: 4,
            rn: '1',
            name: 'Тип водосбросного шандорного колодца для расхода гидросмеси:',
            not: '163.jpg',
            val: '',
            um: 'м3/сек',
            isInput: false,
            formula: 'x/3600',
            operands: { x: 164 },
            calcOrder: 111,
            parent: 0,
        },
        {
            id: 164,
            block: 4,
            rn: 'где:',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },
            calcOrder: 110,
            parent: 163,
        },
        {
            id: 165,
            block: 4,
            rn: '',
            name: 'Принимается двухсекционный шандорный колодец с высотой сливающегося слоя воды Нc=0,25м',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
            parent: 163,
        },
        {
            id: 166,
            block: 4,
            rn: '2',
            name: 'Расход воды через двухсекционный шандорный колодец:',
            not: '166.jpg',
            val: '',
            um: 'м3/сек',
            isInput: false,
            formula: 'm*b*h*pow(2*9.8*h,1/2)',
            operands: { m: 167, b: 168,  h: 169 },
            calcOrder: 112,
            parent: 0,
        },
        {
            id: 167,
            block: 4,
            rn: 'где:',
            name: 'коэффициент расхода (0,3-0,55)',
            not: '167.jpg',
            val: '0.50',
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 166,
        },
        {
            id: 168,
            block: 4,
            rn: '',
            name: 'ширина водосливной части колодца',
            not: '168.jpg',
            val: '2.00',
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 166,
        },
        {
            id: 169,
            block: 4,
            rn: '',
            name: 'высота слоя сливающейся воды на стенкой шандора (0,1-0,35м)',
            not: '169.jpg',
            val: '0.25',
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 166,
        },
        {
            id: 170,
            block: 4,
            rn: '3',
            name: 'Число водосбросных колодцев на карте намыва:',
            not: '170.jpg',
            val: '',
            um: 'шт',
            isInput: false,
            formula: 'x*y/z',
            operands: { x: 171, y: 172, z: 173 },
            round: 0,
            calcOrder: 115,
            parent: 0,
        },
        {
            id: 171,
            block: 4,
            rn: 'где:',
            name: 'коэффициент, учитывающий потери воды (0,8-0,85)',
            not: '171.jpg',
            val: '0.80',
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 170,
        },
        {
            id: 172,
            block: 4,
            rn: '',
            name: 'расход воды через двухсекционный шандорный колодец',
            not: '172.jpg',
            val: '',
            um: 'м3/сек',
            isInput: false,
            formula: 'x',
            operands: { x: 166 },
            calcOrder: 113,
            parent: 170,
        },
        {
            id: 173,
            block: 4,
            rn: '',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/сек',
            isInput: false,
            formula: 'x',
            operands: { x: 163 },
            calcOrder: 114,
            parent: 170,
        },
        {
            id: 174,
            block: 4,
            rn: '4',
            name: 'Расход воды через водосбросную трубу:',
            not: '174.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'm*w*pow(2*9.8*h,1/2)',
            operands: { m: 177, w: 176, h: 175 },
            calcOrder: 121,
            parent: 0,
        },
        {
            id: 175,
            block: 4,
            rn: 'где:',
            name: 'напор воды над осью трубы',
            not: '175.jpg',
            val: 0.90,
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 174,
        },
        {
            id: 176,
            block: 4,
            rn: '',
            name: 'площадь поперечного  сечения трубы',
            not: '176.jpg',
            val: '',
            um: 'м2',
            isInput: false,
            formula: 'x',
            operands: { x: 178 },
            calcOrder: 119,
            parent: 174,
        },
        {
            id: 177,
            block: 4,
            rn: '',
            name: 'коэффициент расхода',
            not: '177.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'x',
            operands: { x: 180 },
            calcOrder: 120,
            parent: 174,
        },
        {
            id: 178,
            block: 4,
            rn: '5',
            name: 'Площадь поперечного  сечения трубы:',
            not: '178.jpg',
            val: '',
            um: 'м2',
            isInput: false,
            formula: '3.14*d*d/4',
            operands: { d: 179 },
            calcOrder: 116,
            parent: 0,
        },
        {
            id: 179,
            block: 4,
            rn: 'где:',
            name: 'диаметр водосбросной трубы',
            not: '179.jpg',
            val: 0.60,
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 178,
        },
        {
            id: 180,
            block: 4,
            rn: '6',
            name: 'Коэффициент расхода:',
            not: '180.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: '1/pow(1+j*l/d,1/2)',
            operands: { j: 183, l: 181, d: 182 },
            calcOrder: 118,
            parent: 0,
        },
        {
            id: 181,
            block: 4,
            rn: 'где:',
            name: 'длина водосбросной трубы',
            not: '181.jpg',
            val: 33.00,
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 180,
        },
        {
            id: 182,
            block: 4,
            rn: '',
            name: 'диаметр водосбросной трубы',
            not: '182.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 179 },
            calcOrder: 117,
            parent: 180,
        },
        {
            id: 183,
            block: 4,
            rn: '',
            name: 'коэффициент гидравлического сопротивления',
            not: '183.jpg',
            val: 0.015,
            um: '',
            isInput: true,
            calcOrder: 0,
            parent: 180,
        },
        {
            id: 184,
            block: 4,
            rn: '7',
            name: 'Расход воды через водосбросную трубу должен быть:',
            not: '184.jpg',
            val: '',
            um: '',
            isInput: false,
            formula: 'x/y',
            operands: { x: 185, y: 186 },
            calcOrder: 124,
            parent: 0,
            comment: 'Проверка условия',
            commentImg: '184c.jpg',
        },
        {
            id: 185,
            block: 4,
            rn: 'где:',
            name: 'расход воды через водосбросную трубу',
            not: '185.jpg',
            val: '',
            um: 'м3/сек',
            isInput: false,
            formula: 'x',
            operands: { x: 174 },
            calcOrder: 122,
            parent: 180,
        },
        {
            id: 186,
            block: 4,
            rn: '',
            name: 'расход воды через двухсекционный шандорный колодец',
            not: '186.jpg',
            val: '',
            um: 'м3/сек',
            isInput: false,
            formula: 'x',
            operands: { x: 166 },
            calcOrder: 123,
            parent: 180,
        },
        {
            id: 187,
            block: 4,
            rn: '8',
            name: 'Уклон трубы:',
            not: '187.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'pow(q,2)/(pow(w,2)*pow(c,2)*r)',
            operands: { q: 185, w: 188, c: 190, r: 189 },
            round: 3,
            calcOrder: 129,
            parent: 0,
        },
        {
            id: 188,
            block: 4,
            rn: 'где:',
            name: 'площадь поперечного сечения трубы',
            not: '176.jpg',
            val: '',
            um: 'м2',
            isInput: false,
            formula: 'x',
            operands: { x: 178 },
            calcOrder: 125,
            parent: 187,
        },
        {
            id: 189,
            block: 4,
            rn: '',
            name: 'гидравлический радиус трубы',
            not: '189.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'd/4',
            operands: { d: 182 },
            round: 3,
            calcOrder: 126,
            parent: 187,
        },
        {
            id: 190,
            block: 4,
            rn: '',
            name: 'коэффициент Шези',
            not: '190.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'pow(r,y)/n',
            operands: { r: 189, y: 192, n: 191 },
            calcOrder: 128,
            parent: 187,
        },
        {
            id: 191,
            block: 4,
            rn: '',
            name: 'коэффициент, учитывающий шероховатость трубы ',
            not: '191.jpg',
            val: 0.013,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 187,
        },
        {
            id: 192,
            block: 4,
            rn: '',
            name: 'показатель степени',
            not: '192.jpg',
            val: '',
            um: '',
            isInput: false,
            formula: '1.5*pow(n,0.5)',
            operands: { n: 191 },
            round: 3,
            calcOrder: 127,
            parent: 187,
            comment: 'при',
            commentImg: '192c.jpg'
        },
        {
            id: 193,
            block: 5,
            rn: '1',
            name: 'Скорость движения частиц по оси потока при входе  в пруд-отстойник:',
            not: '193.jpg',
            val: '',
            um: '-',
            isInput: false,
            formula: 'q/(b*h*3600)',
            operands: { q: 194, b: 195, h: 196 },
            round: 3,
            calcOrder: 131,
            parent: 0,
        },
        {
            id: 194,
            block: 5,
            rn: 'где:',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },
            calcOrder: 130,
            parent: 193,
        },
        {
            id: 195,
            block: 5,
            rn: '',
            name: 'ширина потока гидросмеси (при торцевом выпуске принимается 50м)',
            not: '195.jpg',
            val: 50.00,
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 193,
        },
        {
            id: 196,
            block: 5,
            rn: '',
            name: 'глубина потока гидросмеси на откосе намыва ( из практики 0.1-0.2)',
            not: '196.jpg',
            val: 0.10,
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 193,
        },
        {
            id: 197,
            block: 5,
            rn: '2',
            name: 'Длина откоса намыва:',
            not: '197.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'q/(b*h)',
            operands: { q: 198, b: 199, h: 200 },
            calcOrder: 139,
            parent: 0,
        },
        {
            id: 198,
            block: 5,
            rn: 'где:',
            name: 'суточная производительность земснаряда по грунту',
            not: '198.jpg',
            val: '',
            um: 'м3/сут',
            isInput: false,
            formula: '(x*t*n)/(1-m+q)',
            operands: { x: 201, t: 202, n: 203, m: 204, q: 205 },
            calcOrder: 138,
            parent: 197,
        },
        {
            id: 199,
            block: 5,
            rn: '',
            name: 'ширина потока гидросмеси (при торцевом выпуске принимается 50м)',
            not: '195.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 195 },
            calcOrder: 132,
            parent: 197,
        },
        {
            id: 200,
            block: 5,
            rn: '',
            name: 'интенсивность намыва (для песка 0.1-1.0 м/сут)',
            not: '200.jpg',
            val: 1.00,
            um: 'м/сут',
            isInput: true,
            calcOrder: 0,
            parent: 197,
        },
        {
            id: 201,
            block: 5,
            rn: '',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },
            calcOrder: 133,
            parent: 197,
        },
        {
            id: 202,
            block: 5,
            rn: '',
            name: 'продолжительность смены',
            not: '39.jpg',
            val: '',
            um: 'ч',
            isInput: false,
            formula: 'x',
            operands: { x: 39 },
            calcOrder: 134,
            parent: 197,
        },
        {
            id: 203,
            block: 5,
            rn: '',
            name: 'число смен в сутки',
            not: '40.jpg',
            val: '',
            um: '',
            isInput: false,
            formula: 'x',
            operands: { x: 40 },
            calcOrder: 135,
            parent: 197,
        },
        {
            id: 204,
            block: 5,
            rn: '',
            name: 'средняя пористость породы',
            not: '44.jpg',
            val: '',
            um: 'доли ед.',
            isInput: false,
            formula: 'x',
            operands: { x: 44 },
            calcOrder: 136,
            parent: 197,
        },
        {
            id: 205,
            block: 5,
            rn: '',
            name: 'удельный расход воды',
            not: '23.jpg',
            val: '',
            um: 'м3/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 43 },
            calcOrder: 137,
            parent: 197,
        },
        {
            id: 206,
            block: 5,
            rn: '3',
            name: 'Минимальный путь осаждения частиц d=1,00мм на карте намыва:',
            not: '206.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '0.82*(v/w)*h',
            operands: { v: 209, w: 208, h: 207 },
            calcOrder: 141,
            parent: 0,
        },
        {
            id: 207,
            block: 5,
            rn: 'где:',
            name: 'глубина воды в пруду-отстойнике (1-5м)',
            not: '207.jpg',
            val: 1.50,
            um: 'м',
            isInput: true,
            calcOrder: 0,
            parent: 206,
        },
        {
            id: 208,
            block: 5,
            rn: '',
            name: 'максимальная гидравлическая крупность частиц',
            not: '208.jpg',
            val: 0.108,
            um: 'м/сек',
            isInput: true,
            calcOrder: 0,
            parent: 206,
        },
        {
            id: 209,
            block: 5,
            rn: '',
            name: 'скорость движения частиц по оси потока при входе  в пруд-отстойник',
            not: '209.jpg',
            val: '',
            um: 'м/сек',
            isInput: false,
            formula: 'x',
            operands: { x: 193 },
            round: 3,
            calcOrder: 140,
            parent: 206,
        },
        {
            id: 210,
            block: 5,
            rn: '4',
            name: 'Максимальный путь осаждения частицы d=0.2мм в пруду отстойнике карты:',
            not: '210.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: '1.18*(v/w)*h',
            operands: { v: 211, w: 212, h: 213 },
            calcOrder: 144,
            parent: 0,
        },
        {
            id: 211,
            block: 5,
            rn: 'где:',
            name: 'скорость движения частиц по оси потока при входе  в пруд-отстойник',
            not: '209.jpg',
            val: '',
            um: 'м/сек',
            isInput: false,
            formula: 'x',
            operands: { x: 193 },
            round: 3,
            calcOrder: 142,
            parent: 210,
        },
        {
            id: 212,
            block: 5,
            rn: '',
            name: 'минимальная гидравлическая крупность частиц d=0.2мм',
            not: '212.jpg',
            val: 0.019,
            um: 'м/сек',
            isInput: true,
            calcOrder: 0,
            parent: 210,
        },
        {
            id: 213,
            block: 5,
            rn: '',
            name: 'глубина воды в пруду-отстойнике',
            not: '207.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 207 },
            calcOrder: 143,
            parent: 210,
        },
        {
            id: 214,
            block: 5,
            rn: '5',
            name: 'Средний уклон намывной поверхности карты:',
            not: '214.jpg',
            val: '',
            um: '%',
            isInput: false,
            formula: '(a*pow(s,1/3))/pow(1.6*q/l,0.5)',
            operands: { a: 215, s: 218, q: 216, l: 217 },
            calcOrder: 151,
            parent: 0,
        },
        {
            id: 215,
            block: 5,
            rn: 'где:',
            name: 'коэффициент , зависящий от состава пород',
            not: '215.jpg',
            val: 3.50,
            um: '',
            isInput: true,
            calcOrder: 0,
            parent: 214,
        },
        {
            id: 216,
            block: 5,
            rn: '',
            name: 'расход гидросмеси, подаваемый на карту',
            not: '50.jpg',
            val: '',
            um: 'л/с',
            isInput: false,
            formula: 'x*1000',
            operands: { x: 163 },
            round: 0,
            calcOrder: 145,
            parent: 214,
        },
        {
            id: 217,
            block: 5,
            rn: '',
            name: 'длина откоса намыва',
            not: '217.jpg',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 197 },
            calcOrder: 146,
            parent: 214,
        },
        {
            id: 218,
            block: 5,
            rn: '',
            name: 'консистенция гидросмеси',
            not: '218.jpg',
            val: '',
            um: '%',
            isInput: false,
            formula: '100*(g-o)/(t-o)*t/o',
            operands: { g: 220, o: 219, t: 221 },
            round: 0,
            calcOrder: 150,
            parent: 214,
        },
        {
            id: 219,
            block: 5,
            rn: '',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 24 },
            calcOrder: 147,
            parent: 214,
        },
        {
            id: 220,
            block: 5,
            rn: '',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 41 },
            calcOrder: 148,
            parent: 214,
        },       
        {
            id: 221,
            block: 5,
            rn: '',
            name: 'средняя плотность частиц породы',
            not: '45.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 45 },
            calcOrder: 149,
            parent: 214,
        },
        {
            id: 300,
            block: 7,
            rn: '',
            name: '1. Расчетные параметры работы земснаряда',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
            parent: 0,
        },
        {
            id: 301,
            block: 7,
            rn: '1.1',
            name: 'Средняя плотность гидросмеси',
            not: '',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 41 },
            round: 3,
            calcOrder: 301,
            parent: 301,
        },
        {
            id: 302,
            block: 7,
            rn: '1.2',
            name: 'Производительность земснаряда по гидросмеси',
            not: '',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },
            round: 0,
            calcOrder: 302,
            parent: 302,
        },
        {
            id: 303,
            block: 7,
            rn: '1.3',
            name: 'Техническая производительность земснаряда по породе (грунту)',
            not: '',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 49 },
            round: 0,
            calcOrder: 303,
            parent: 303,
        },
        {
            id: 304,
            block: 7,
            rn: '1.4',
            name: 'Сменная производительность земснаряда по породе (грунту)',
            not: '',
            val: '',
            um: 'м3/смена',
            isInput: false,
            formula: 'x',
            operands: { x: 53 },
            round: 0,
            calcOrder: 304,
            parent: 304,
        },
        {
            id: 310,
            block: 7,
            rn: '',
            name: '2. Расчетные параметры гидротранспортной системы',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
            parent: 0,
        },
        {
            id: 311,
            block: 7,
            rn: '2.1',
            name: 'Диаметр пульпопровода',
            not: '',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 26 },
            round: 3,
            calcOrder: 311,
            parent: 311,
        },
        {
            id: 312,
            block: 7,
            rn: '2.2',
            name: 'Критическая скорость гидросмеси в пульпопроводе',
            not: '',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 73 },
            calcOrder: 312,
            parent: 312,
        },
        {
            id: 313,
            block: 7,
            rn: '2.3',
            name: 'Действительная скорость гидросмеси в пульпопроводе',
            not: '',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 81 },
            calcOrder: 313,
            parent: 313,
        },
        {
            id: 314,
            block: 7,
            rn: '2.4',
            name: 'Удельные потери напора при движении гидросмеси',
            not: '',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 89 },
            round: 3,
            calcOrder: 314,
            parent: 314,
        },
        {
            id: 315,
            block: 7,
            rn: '2.5',
            name: 'Потери напора во всасывающем трубопроводе земснаряда',
            not: '',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 96 },
            calcOrder: 315,
            parent: 315,
        },
        {
            id: 316,
            block: 7,
            rn: '2.6',
            name: 'Скорость во всасывающем трубопроводе земснаряда',
            not: '',
            val: '',
            um: 'м/с',
            isInput: false,
            formula: 'x',
            operands: { x: 106 },
            calcOrder: 316,
            parent: 316,
        },
        {
            id: 317,
            block: 7,
            rn: '2.7',
            name: 'Потери напора в гидротранспортной системе',
            not: '',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 120 },
            calcOrder: 317,
            parent: 317,
        },
        {
            id: 318,
            block: 7,
            rn: '2.8',
            name: 'Напор земснаряда по гидросмеси',
            not: '',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 154 },
            calcOrder: 318,
            parent: 318,
        },
        {
            id: 319,
            block: 7,
            rn: '2.9',
            name: 'Требуемое число насосов в гидротранспортной системе',
            not: '',
            val: '',
            um: 'шт',
            isInput: false,
            formula: 'x',
            operands: { x: 152 },
            calcOrder: 319,
            parent: 319,
        },
        {
            id: 330,
            block: 7,
            rn: '',
            name: '3. Расчетные параметры карты намыва',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
            parent: 0,
        },
        {
            id: 331,
            block: 7,
            rn: '3.1',
            name: 'Длина откоса намыва',
            not: '',
            val: '',
            um: 'м',
            isInput: false,
            formula: 'x',
            operands: { x: 197 },
            calcOrder: 331,
            parent: 331,
        },
        {
            id: 332,
            block: 7,
            rn: '3.2',
            name: 'Средний уклон намывной поверхности карты',
            not: '',
            val: '',
            um: '%',
            isInput: false,
            formula: 'x',
            operands: { x: 214 },
            calcOrder: 332,
            parent: 332,
        },
        {
            id: 333,
            block: 7,
            rn: '3.3',
            name: 'Консистенция гидросмеси',
            not: '',
            val: '',
            um: '%',
            isInput: false,
            formula: 'x',
            operands: { x: 218 },
            calcOrder: 333,
            parent: 333,
        },
        {
            id: 340,
            block: 7,
            rn: '',
            name: '4. Расчетные параметры водосбросных сооружений на карте намыва',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
            parent: 0,
        },
        {
            id: 341,
            block: 7,
            rn: '4.1',
            name: 'Расход гидросмеси',
            not: '',
            val: '',
            um: 'м3/с',
            isInput: false,
            formula: 'x',
            operands: { x: 163 },
            calcOrder: 341,
            parent: 341,
        },
        {
            id: 342,
            block: 7,
            rn: '4.2',
            name: 'Расход воды через водосбросной колодец',
            not: '',
            val: '',
            um: 'м3/с',
            isInput: false,
            formula: 'x',
            operands: { x: 166 },
            calcOrder: 342,
            parent: 342,
        },
        {
            id: 343,
            block: 7,
            rn: '4.3',
            name: 'Число водосбросных колодцев',
            not: '',
            val: '',
            um: 'шт',
            isInput: false,
            formula: 'x',
            operands: { x: 170 },
            calcOrder: 343,
            parent: 343,
        },
        {
            id: 344,
            block: 7,
            rn: '4.4',
            name: 'Расход воды через водосбросную трубу',
            not: '',
            val: '',
            um: 'м3/с',
            isInput: false,
            formula: 'x',
            operands: { x: 174 },
            calcOrder: 344,
            parent: 344,
        },
        {
            id: 345,
            block: 7,
            rn: '4.5',
            name: 'Уклон водосбросной трубы',
            not: '',
            val: '',
            um: '',
            isInput: false,
            formula: 'x',
            operands: { x: 187 },
            round: 3,
            calcOrder: 345,
            parent: 345,
        },
    ];
}