export default function getItems() {
    return [
        {
            id: 1,
            block: 1,
            rn: '1', // row number
            name: 'Полезное ископаемое, в т.ч.:',
            not: '1.jpg', // notation
            val: 'песок',  // value
            um: '', // unit of measure
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 2,
            block: 1,
            rn: '1.1',
            name: 'Песок мелкозернистый:',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 3,
            block: 1,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '3.jpg',
            val: 0.2,
            um: '-',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 4,
            block: 1,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '4.jpg',
            val: 91,
            um: '%',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 5,
            block: 1,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.2,
            um: 'мм',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 6,
            block: 1,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.3,
            um: 'доли ед.',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 7,
            block: 1,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.65,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 8,
            block: 1,
            rn: '1.2',
            name: 'Пылеватые и глинистые частицы',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 9,
            block: 1,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '9.jpg',
            val: 0.02,
            um: '-',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 10,
            block: 1,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '10.jpg',
            val: 4.08,
            um: '%',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 11,
            block: 1,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.1,
            um: 'мм',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 12,
            block: 1,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.4,
            um: 'доли ед.',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 13,
            block: 1,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.7,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 14,
            block: 1,
            rn: '1.3',
            name: 'Гравий',
            not: '',
            val: '',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 15,
            block: 1,
            rn: 'a)',
            name: 'Коэффицент транспортабельности фракций',
            not: '15.jpg',
            val: 0.8,
            um: '-',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 16,
            block: 1,
            rn: 'б)',
            name: 'Процентное содержание в толще',
            not: '16.jpg',
            val: 4.42,
            um: '%',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 17,
            block: 1,
            rn: 'в)',
            name: 'Диаметр частиц',
            not: '5.jpg',
            val: 0.63,
            um: 'мм',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 18,
            block: 1,
            rn: 'г)',
            name: 'Пористость породы',
            not: '6.jpg',
            val: 0.3,
            um: 'доли ед.',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 19,
            block: 1,
            rn: 'д)',
            name: 'Плотность частиц породы',
            not: '7.jpg',
            val: 2.65,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 20,
            block: 1,
            rn: '2',
            name: 'Общий объем добычи за весь период разработки карьера',
            not: '20.jpg',
            val: 13959359,
            um: 'м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 21,
            block: 1,
            rn: '2.1',
            name: 'Сезонный объем добычи',
            not: '21.jpg',
            val: 664740,
            um: 'м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 22,
            block: 1,
            rn: '3',
            name: 'Средняя плотность породы в естественном залегании',
            not: '22.jpg',
            val: 1.6,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 23,
            block: 1,
            rn: '4',
            name: 'Удельный расход воды на разработку грунта',
            not: '23.jpg',
            val: 7,
            um: 'м3/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 24,
            block: 1,
            rn: '5',
            name: 'Плотность воды',
            not: '24.jpg',
            val: 1,
            um: 'т/м3',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 25,
            block: 1,
            rn: '6',
            name: 'Тип земснаряда',
            not: '',
            val: 'Гидромех 2000',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 26,
            block: 1,
            rn: '7',
            name: 'Диаметр пульпопровода',
            not: '26.jpg',
            val: 0.426,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 27,
            block: 1,
            rn: '8',
            name: 'Диаметр всасывающей трубы',
            not: '27.jpg',
            val: 0.6,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 28,
            block: 1,
            rn: '9',
            name: 'Длина плавучего участка магистрального пульпопровода',
            not: '28.jpg',
            val: 200,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 29,
            block: 1,
            rn: '10',
            name: 'Длина участка берегового магистрального пульпопровода до карты намыва',
            not: '29.jpg',
            val: 700,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 30,
            block: 1,
            rn: '11',
            name: 'Длина наклонного участка пульпопровода при переходе от плавучего к магистральному',
            not: '30.jpg',
            val: 30,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 31,
            block: 1,
            rn: '12',
            name: 'Угол наклона трубы (борта карьера)',
            not: '31.jpg',
            val: 30,
            um: 'град',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 32,
            block: 1,
            rn: '13',
            name: 'Длина намывного распределительного пульпопровода на картах намыва',
            not: '32.jpg',
            val: 150,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 33,
            block: 1,
            rn: '14',
            name: 'Грунтовый насос',
            not: '1.jpg',
            val: 'ГРаУ 2000-63',
            um: '',
            isInput: false,
            calcOrder: 0,
        },
        {
            id: 34,
            block: 1,
            rn: '15',
            name: 'Подача грунтового насоса по воде',
            not: '34.jpg',
            val: 2000,
            um: 'м3/ч',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 35,
            block: 1,
            rn: '16',
            name: 'Напор насоса',
            not: '35.jpg',
            val: 63,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 36,
            block: 1,
            rn: '17',
            name: 'Геодезическая высота всасывания',
            not: '36.jpg',
            val: -0.5,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 37,
            block: 1,
            rn: '18',
            name: 'Глубина разработки грунта',
            not: '37.jpg',
            val: 13.5,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 38,
            block: 1,
            rn: '19',
            name: 'Высота подъема гидросмеси',
            not: '38.jpg',
            val: 10,
            um: 'м',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 39,
            block: 1,
            rn: '20',
            name: 'Продолжительность смены',
            not: '39.jpg',
            val: 8,
            um: 'ч',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 40,
            block: 1,
            rn: '21',
            name: 'Число рабочих смен в сутки',
            not: '40.jpg',
            val: 2,
            um: '',
            isInput: true,
            calcOrder: 0,
        },
        {
            id: 41,
            block: 2,
            rn: '1',
            name: 'Средняя плотность гидросмеси:',
            not: '41.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: '(y*q+u*(1-m))/(q+(1-m))',
            operands: { y: 42, q: 43, u: 45, m: 44 },
            round: 3,
            calcOrder: 5,
            parent: 0,
        },
        {
            id: 42,
            block: 2,
            rn: 'где:',
            name: 'плотность воды',
            not: '24.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 24 },
            calcOrder: 1,
            parent: 41,
        },
        {
            id: 43,
            block: 2,
            rn: '',
            name: 'удельный расход воды',
            not: '23.jpg',
            val: '',
            um: 'м3/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 23 },
            calcOrder: 2,
            parent: 41,
            comment: 'табл. 2.22 ОНТП 18-85'
        },
        {
            id: 44,
            block: 2,
            rn: '',
            name: 'средняя пористость породы, доли ед',
            not: '44.jpg',
            val: '',
            um: 'доли ед.',
            isInput: false,
            formula: '(x+y+z)/3',
            operands: { x: 6, y: 12, z: 18 },
            calcOrder: 3,
            parent: 41,
        },
        {
            id: 45,
            block: 2,
            rn: '',
            name: 'средняя плотность частиц породы',
            not: '45.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: '(x+y+z)/3',
            operands: { x: 7, y: 13, z: 19 },
            calcOrder: 4,
            parent: 41,
        },
        {
            id: 46,
            block: 2,
            rn: '2',
            name: 'Производительность земснаряда по гидросмеси:',
            not: '46.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x/y',
            operands: { x: 47, y: 48 },
            round: 0,
            calcOrder: 8,
            parent: 0,
        },
        {
            id: 47,
            block: 2,
            rn: 'где:',
            name: 'подача грунтового насоса по воде, м3/ч',
            not: '47.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 34 },
            calcOrder: 6,
            parent: 46,
        },
        {
            id: 48,
            block: 2,
            rn: '',
            name: 'средняя плотность гидросмеси',
            not: '48.jpg',
            val: '',
            um: 'т/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 41 },
            round: 3,
            calcOrder: 7,
            parent: 46,
        },
        {
            id: 49,
            block: 2,
            rn: '3',
            name: 'Расчетная техническая производительность земснаряда по породе (грунту):',
            not: '49.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x/(q+(1-m))',
            operands: { x: 50, q: 51, m: 52 },
            round: 0,
            calcOrder: 12,
            parent: 0,
        },
        {
            id: 50,
            block: 2,
            rn: 'где:',
            name: 'производительность земснаряда по гидросмеси',
            not: '50.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 46 },  
            round: 0,
            calcOrder: 9,
            parent: 49,
        },
        {
            id: 51,
            block: 2,
            rn: '',
            name: 'удельный расход воды',
            not: '23.jpg',
            val: '',
            um: 'м3/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 43 },
            calcOrder: 10,
            parent: 49,
        },
        {
            id: 52,
            block: 2,
            rn: '',
            name: 'средняя пористость породы, доли ед',
            not: '44.jpg',
            val: '',
            um: 'доли ед.',
            isInput: false,
            formula: 'x',
            operands: { x: 44 },
            calcOrder: 11,
            parent: 49,
        },
        {
            id: 53,
            block: 2,
            rn: '4',
            name: 'Расчетная сменная производительность земснаряда по грунту:',
            not: '53.jpg',
            val: '',
            um: 'м3/смена',
            isInput: false,
            formula: 'x*t*k*l*m',
            operands: { x: 49, t: 55, k: 56, l: 57, m: 58 },
            round: 0,
            calcOrder: 15,
            parent: 0,
        },
        {
            id: 54,
            block: 2,
            rn: 'где:',
            name: 'расчетная техническая производительность земснаряда по породе (грунту)',
            not: '54.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 49 },    //  49
            calcOrder: 13,
            parent: 53,
        },
        {
            id: 55,
            block: 2,
            rn: '',
            name: 'продолжительность смены',
            not: '39.jpg',
            val: '',
            um: 'ч',
            isInput: false,
            formula: 'x',
            operands: { x: 39 },
            calcOrder: 14,
            parent: 53,
        },
        {
            id: 56,
            block: 2,
            rn: '',
            name: 'коэффициент использования внутрисменного времени',
            not: '56.jpg',
            val: 0.75,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 57,
            block: 2,
            rn: '',
            name: 'коэффициент учитывающий межсменные и другие простои',
            not: '57.jpg',
            val: 0.95,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 58,
            block: 2,
            rn: '',
            name: 'коэффициент, учитывающий засоренность забоя',
            not: '58.jpg',
            val: 1.00,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 59,
            block: 2,
            rn: '',
            name: 'коэффициент, учитывающий работу земснаряда совместно со станциями перекачивания',
            not: '59.jpg',
            val: 1.00,
            um: '-',
            isInput: true,
            calcOrder: 0,
            parent: 53,
        },
        {
            id: 60,
            block: 2,
            rn: '5',
            name: 'Количество машиносмен на добычных работах для одного земснаряда за один сезон разработки карьера:',
            not: '60.jpg',
            val: '',
            um: 'машиносмен',
            isInput: false,
            formula: 'x/y',
            operands: { x: 61, y: 62 },
            round: 0,
            calcOrder: 18,
            parent: 0,
        },
        {
            id: 61,
            block: 2,
            rn: 'где:',
            name: 'сезонный объем добычи',
            not: '61.jpg',
            val: '',
            um: 'м3',
            isInput: false,
            formula: 'x',
            operands: { x: 21 },
            calcOrder: 16,
            parent: 60,
        },
        {
            id: 62,
            block: 2,
            rn: '',
            name: 'расчетная сменная производительность земснаряда по грунту',
            not: '62.jpg',
            val: '',
            um: 'м3/смена',
            isInput: false,
            formula: 'x',
            operands: { x: 53 },
            calcOrder: 17,
            parent: 60,
        },
        {
            id: 63,
            block: 2,
            rn: '6',
            name: 'Количество машиносмен на добычных работах для одного земснаряда за весь период разработки карьера:',
            not: '63.jpg',
            val: '',
            um: 'машиносмен',
            isInput: false,
            formula: 'x/y',
            operands: { x: 64, y: 65 },
            round: 0,
            calcOrder: 21,
            parent: 0,
        },
        {
            id: 64,
            block: 2,
            rn: 'где:',
            name: 'общий объем добычи за весь период разработки карьера',
            not: '64.jpg',
            val: '',
            um: 'м3',
            isInput: false,
            formula: 'x',
            operands: { x: 20 },
            calcOrder: 19,
            parent: 63,
        },
        {
            id: 65,
            block: 2,
            rn: '',
            name: 'расчетная сменная производительность земснаряда по грунту',
            not: '65.jpg',
            val: '',
            um: 'м3/сутки',
            isInput: false,
            formula: 'x',
            operands: { x: 53 },
            calcOrder: 20,
            parent: 63,
        },
        {
            id: 66,
            block: 2,
            rn: '7',
            name: 'Расход воды для обеспечения земснаряда:',
            not: '66.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x*q+y',
            operands: { x: 67, q: 68, y: 69 },
            round: 0,
            calcOrder: 25,
            parent: 0,
        },
        {
            id: 67,
            block: 2,
            rn: 'где:',
            name: 'расчетная производительность земснаряда по грунту',
            not: '54.jpg',
            val: '',
            um: 'м3/ч',
            isInput: false,
            formula: 'x',
            operands: { x: 49 },
            calcOrder: 22,
            parent: 66,
        },
        {
            id: 68,
            block: 2,
            rn: '',
            name: 'удельный расход воды',
            not: '23.jpg',
            val: '',
            um: 'м3/м3',
            isInput: false,
            formula: 'x',
            operands: { x: 23 },
            calcOrder: 23,
            parent: 66,
        },
        {
            id: 69,
            block: 2,
            rn: '',
            name: 'сумма потерь воды на фильтрацию и испарение',
            not: '69.jpg',
            val: '',
            um: 'м3',
            isInput: false,
            formula: '0.1*x*y',
            operands: { x: 67, y: 68 },
            calcOrder: 24,
            parent: 66,
            comment: '10% от Qп.з*q'
        },
    ];
}